# Automatically call APIs
name: MSO-E5-Dev-AutoRenew

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
  schedule:
    - cron: "10 */2 * * *"
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: (github.event.repository.owner.id == github.event.sender.id) || ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}  # Self-ordered start
    #if: github.event.repository.owner.id == github.event.sender.id  # Self-ordered start
    name: Build and call API
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: true # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        check-latest: true
    - name: Install required Python packages
      run: |
        pip install requests
    - name: Update new refresh token and call APIs
      run: | 
        cp main.py temp.py
        echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log
        python3 temp.py ${{ secrets.CONFIG_ID }} ${{ secrets.CONFIG_KEY }} ${{ secrets.REFRESH_TOKEN }} ${{ secrets.GH_TOKEN }} ${{ github.repository }}
    - name: Remove temporary files
      run: | 
        rm -f temp.py
    - name: Commit
      run: |
        git config --global user.email ls@hung.vn
        git config --global user.name Hung
        git add .
        git commit -m "Update new refresh token and call APIs" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        #force_with_lease: true
